# Create group
POST http://localhost:8000/groups/create
Content-Type: application/json

{
  "name": "NewGroup",
  "password": "geheimesPasswort"
}

###

# Get all groups
GET http://localhost:8000/groups/ 
Content-Type: application/json

###

# Get specific group
GET http://localhost:8000/groups/19
Content-Type: application/json

###

# Update group
PUT http://localhost:8000/groups/10
Content-Type: application/json

{
  "name": "changedGroup",
  "password": "changedPassword"
}

###

# Delete group
DELETE http://localhost:8000/groups/18
Content-Type: application/json