POST http://localhost:8000/users/signup
Content-Type: application/json

{
    "username": "test",
    "email": "testing@user.com",
    "password": "abc"
}

###
//dGVzdDphYmM= correct
//dGVzdDp3cm9uZw== wrong password
//d3Jvbmc6d3Jvbmc= wrong data
POST http://localhost:8000/users/login
Authorization: Bearer dGVzdGluZzphYmM=

###
POST http://localhost:8000/users/logout
