# Create group
POST http://localhost:8080/groups/create
Content-Type: application/json

{
  "name": "Test Group",
  "colorCode": "DDDDDD"
}

###

# Get all groups
GET http://localhost:8000/groups/ 
Content-Type: application/json

###

# Get specific group
GET http://localhost:8000/groups/102
Content-Type: application/json

###
# Invite and add user to group

GET http://localhost:8000/groups/invitation/lXWn7
Content-Type: application/json

###

# Update group
PUT http://localhost:8000/groups/13
Content-Type: application/json

{
  "name": "changedGroup",
  "password": "changedPassword",
  "colorCode" : "FAFAFA"
}

###

# Delete group
DELETE http://localhost:8000/groups/109
Content-Type: application/json