# Create group
POST http://localhost:8000/groups/create
Content-Type: application/json

{
  "name": "Group for  Pending Test",
  "colorCode": "DDDDDD",
  "password": "abc"
}

###
# Get Group
GET http://localhost:8000/groups/19

###

GET http://localhost:8000/groups

###

# Get all teams for group
GET http://localhost:8000/groups/teams/19
Content-Type: application/json

###

# Get specific group
GET http://localhost:8000/groups/27
Content-Type: application/json

###

# Invite and add user to group
GET http://localhost:8000/groups/invitation?invCode=KtZtK&password=abc

###
# Update group
PUT http://localhost:8000/groups/1
Content-Type: application/json

{
  "name": "changedGroup",
  "colorCode" : "FAFAFA",
  "password": "password"
}

###

# Delete group
DELETE http://localhost:8000/groups/26
Content-Type: application/json