# Create group
POST http://localhost:8000/groups/create
Content-Type: application/json

{
  "name": "Very New Group",
  "password": "passwort"
}

###

# Get all groups
GET http://localhost:8000/groups/ 
Content-Type: application/json

###

# Get specific group
GET http://localhost:8000/groups/10
Content-Type: application/json

###
# Invite and add user to group
GET http://localhost:8000/groups/invitation/IG5qD
Content-Type: application/json

###

# Update group
PUT http://localhost:8000/groups/10
Content-Type: application/json

{
  "name": "changedGroup",
  "password": "changedPassword"
}

###

# Delete group
DELETE http://localhost:8000/groups/16
Content-Type: application/json