# Create team
POST http://localhost:8000/teams
Content-Type: application/json

{
  "groupId": 25,
  "name": "Very New Team 3",
  "colorCode": "FFFFFF"
}

###

# Get all teams
GET http://localhost:8000/teams/ 
Content-Type: application/json

###

# Get one team
GET http://localhost:8000/teams/12
Content-Type: application/json

###

# Add member
POST http://localhost:8000/teams/member?teamId=30&userId=2

###

# Remove member

###

# Update team
PUT http://localhost:8000/teams/12
Content-Type: application/json

{
  "name": "changedTeamName",
  "colorCode": "FFFFFF"
}
###



###

# Delete team
DELETE http://localhost:8000/teams/9
Content-Type: application/json