# Create team
POST http://localhost:8000/teams
Content-Type: application/json

{
  "groupId": 1,
  "name": "Very New Team 3",
  "colorCode": "FFFFFF"
}

###

# Get all teams
GET http://localhost:8000/teams/ 
Content-Type: application/json

###

# Get one team
GET http://localhost:8000/teams/9
Content-Type: application/json

###

# Update team
PUT http://localhost:8000/teams/9
Content-Type: application/json

{
  "groupId": 1231239,
  "name": "Changed Team Name 2",
  "colorCode": "FFFFFF"
}
###



###

# Delete team
DELETE http://localhost:8000/teams/9
Content-Type: application/json