POST http://localhost:8000/users/signup
Content-Type: application/json

{
    "username": "yakup",
    "email": "yakup@user.com",
    "password": "abc"
}

###
//dGVzdDphYmM= correct
//dGVzdDp3cm9uZw== wrong password
//d3Jvbmc6d3Jvbmc= wrong data
//YWRtaW46YWRtaW4xMjM= admin
POST http://localhost:8000/users/login
Authorization: Bearer eWFrdXA6YWJj


###
POST http://localhost:8000/users/logout

###
GET http://localhost:8000/users/1

###
GET http://localhost:8000/users/groups/

###
PUT http://localhost:8000/users/1
Content-Type: application/json

{
    "username": "name"
}

###
DELETE http://localhost:8000/users/2

# https://smartcalendarapi.herokuapp.com/
